import jsPDF from 'jspdf'

export function generateIssuePDF(issue, aiResult) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  // Header
  doc.setFillColor(15, 43, 78)
  doc.rect(0, 0, pageWidth, 30, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('VANGUARD', 14, 18)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('AI-Powered Community Protection Platform', 14, 25)

  // Title
  doc.setTextColor(15, 43, 78)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('Community Issue Report', 14, 45)

  // Severity badge color
  const severityColors = {
    green: [22, 163, 74],
    yellow: [234, 179, 8],
    orange: [234, 88, 12],
    red: [220, 38, 38]
  }
  const color = severityColors[aiResult.severity] || [100, 100, 100]
  doc.setFillColor(...color)
  doc.roundedRect(pageWidth - 60, 35, 50, 12, 3, 3, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text(aiResult.severityLabel || aiResult.severity.toUpperCase(), 
           pageWidth - 35, 43, { align: 'center' })

  // Issue details
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('Issue Details', 14, 60)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(`Category: ${aiResult.categoryLabel || aiResult.category}`, 14, 70)
  doc.text(`Reported: ${new Date().toLocaleString('en-IN')}`, 14, 78)
  doc.text(`Location: ${issue.address || 'Community Area'}`, 14, 86)
  doc.text(`Ward: ${issue.ward || 'N/A'} | Village: ${issue.village || 'N/A'}`, 14, 94)

  // AI Analysis
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text('AI Analysis', 14, 108)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(`Impact Score: ${aiResult.impactScore}/100`, 14, 118)
  doc.text(`Risk Type: ${aiResult.riskType}`, 14, 126)
  doc.text(`Recommended Authority: ${aiResult.recommendedAuthority}`, 14, 134)
  doc.text(`Escalation Level: ${aiResult.escalationLevel?.toUpperCase()}`, 14, 142)

  // Risk prediction
  doc.setFont('helvetica', 'bold')
  doc.text('Risk Prediction:', 14, 154)
  doc.setFont('helvetica', 'normal')
  const riskLines = doc.splitTextToSize(aiResult.riskPrediction || '', pageWidth - 28)
  doc.text(riskLines, 14, 162)

  // AI Report
  const reportY = 162 + (riskLines.length * 7) + 10
  doc.setFillColor(240, 245, 255)
  doc.rect(14, reportY - 6, pageWidth - 28, 40, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text('Official Complaint Text:', 18, reportY + 2)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  const reportLines = doc.splitTextToSize(aiResult.reportText || '', pageWidth - 36)
  doc.text(reportLines, 18, reportY + 10)

  // Footer
  doc.setFillColor(15, 43, 78)
  doc.rect(0, 275, pageWidth, 22, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(8)
  doc.text('Generated by VANGUARD AI • ' + new Date().toLocaleString('en-IN'), 
           pageWidth / 2, 284, { align: 'center' })
  doc.text('This report can be submitted to the relevant government authority.', 
           pageWidth / 2, 290, { align: 'center' })

  return doc
}
